name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.1, 8.2, 8.3]

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v4
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, json

      - name: Install composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run unit tests
        run: vendor/bin/phpunit --configuration phpunit.xml
