name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1,8.2]
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v4
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, json, ctype, curl, sockets

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Verify autoload
        run: composer dump-autoload -o

      - name: Run PHPUnit
        run: vendor/bin/phpunit --configuration phpunit.xml